export const returnTableData = [
  {
    hand: "Royal Flush",
    firstLevel: 250,
    secondLevel: 500,
    thirdLevel: 750,
    fourthLevel: 1000,
    fifthLevel: 4000,
  },
  {
    hand: "Straight Flush",
    firstLevel: 50,
    secondLevel: 100,
    thirdLevel: 150,
    fourthLevel: 200,
    fifthLevel: 250,
  },
  {
    hand: "Four of a Kind",
    firstLevel: 25,
    secondLevel: 50,
    thirdLevel: 75,
    fourthLevel: 100,
    fifthLevel: 125,
  },
  {
    hand: "Full House",
    firstLevel: 9,
    secondLevel: 18,
    thirdLevel: 27,
    fourthLevel: 36,
    fifthLevel: 45,
  },
  {
    hand: "Flush",
    firstLevel: 6,
    secondLevel: 12,
    thirdLevel: 18,
    fourthLevel: 24,
    fifthLevel: 30,
  },
  {
    hand: "Straight",
    firstLevel: 4,
    secondLevel: 8,
    thirdLevel: 12,
    fourthLevel: 16,
    fifthLevel: 20,
  },
  {
    hand: "Three of a Kind",
    firstLevel: 3,
    secondLevel: 6,
    thirdLevel: 9,
    fourthLevel: 12,
    fifthLevel: 15,
  },
  {
    hand: "Two Pair",
    firstLevel: 2,
    secondLevel: 4,
    thirdLevel: 6,
    fourthLevel: 8,
    fifthLevel: 10,
  },
  {
    hand: "Jacks or Better",
    firstLevel: 1,
    secondLevel: 2,
    thirdLevel: 3,
    fourthLevel: 4,
    fifthLevel: 5,
  },
];
